CREATE TABLE USER(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255),
  EMAIL VARCHAR(255),
  PASSWORD VARCHAR(255),
  CREATED DATE,
  MODIFIED DATE,
  LAST_LOGIN DATE,
  ACTIVE BOOLEAN
);

CREATE TABLE PHONE (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NUMBER BIGINT,
  CITY_CODE INT,
  COUNTRY_CODE INT,
  USER_ID BIGINT,
  foreign key (USER_ID) references USER(ID)
);

INSERT INTO USER (NAME,EMAIL,PASSWORD,ACTIVE) VALUES('Richard Tapias','registeradmin@gmail.com','admin',TRUE);